### ISSUE TITLE
Poster Review

### ISSUE THREAD

**Issue by gwenchee** [arfc/2019-chee-wm-poster#5]
This issue can be closed after @katyhuff reviews this version of the WM poster. 
[poster.pdf](https://github.com/arfc/2019-chee-wm-poster/files/2899114/poster.pdf)

**Comment by gwenchee** [comment]
associated with https://github.com/arfc/2019-chee-wm-poster/pull/4

**Comment by katyhuff** [comment]
Looking good --- when is this due? Do you know how to have a fabric poster printed with printing.illinois.edu ?

- Paragraph style text is not great for a poster. Bold big ideas, reduce text where possible, add callout boxes ("alertblock") where big ideas can be collected, increase image sizes.
- Can some paragraphs be flowcharts? Diagrams?
- Add an alertblock with your contact info somewhere at the end.
- Although this conference is called "waste management" there actually are a lot of folks who would rather use the term "spent nuclear fuel" or "used nuclear fuel" (including my self). Consider this terminology. 
- Consider just using the Illinois I logo in the corner (just the I), rather than all the way across the top. I have a recent example with arfc logo in one corner and illinois logo in the other corner... will try to remember to point you to a link.
- Waste Conditioning Model doesn't need to be capitalized
- Medium Fidelity Repository Model does not have to be capitalized either.
- Double check grammar in all sentences (first sentence has subject verb plurality mismatch). 
- bold "to study how... repository loading"
- connect the ideas "US historical SNF inventory data" and the sentence beginning "The Unified Database" ... because it's not clear to a naiive reader that you are referring to the same thing. 
- The full name of the UDB is the the UNF-ST&DARDS UDB.
- The sentence beginning "Irradiation... " makes it sound like you ran those scale simulations. Be clear that you did not, who did (ORNL, UDB folks) and why you're telling the reader that this is the case (because you're using the UDB in the simulation).
- inputted is not a word
- There is a missing reference after "UDB reactor agent"
- The bulleted list of the user defined variables is repetitive. Perhaps break it up into variables required for each layer and variables required for each package.
- There should be more space before the section heading "Thermal Model" and "Transient Outside Model"
- the apostrophes on inside and outside in latex should be ``` `inside'``` and ``` `outside'```
- The integral symbols in your equations are way too small.
- I think the particular equations you're citing are the clarified forms from my paper with ted bauer. Those were slightly clarified from the clarified forms in greenberg_application_2012. The forms that appear in the paper that you site (sutton_investigations_2011) are not particularly clear. Consider citing all three papers here... or at least cite greenberg_application_2012.
- Please use this slightly more specific text for the acknowledgement "This research is being performed using funding received from the DOE Office of Nuclear Energy's Nuclear Energy University Program (Project 16-10512, DE-NE0008567) 'Demand-Driven Cycamore Archetypes'."

- a few people in this community are aware of cyder... I believe it should be mentioned that you are refactoring cyder to bring it up to date with new cyclus (or, at least basing this new facility on the general structure of old cyder) and that you are adding this capability to it that was only lumped capacitance in old cyder. (the appropriate citation for cyder is probably huff_rapid_2017.


@juliaroessler do you mind looking over this poster?

**Comment by gwenchee** [comment]
Thank you! I'm leaving for the conference on Sunday, so I just have to print it before then. I think I can figure it out, teddy and greg have done it before, so I will ask them. 

I will make the changes that you mention here, thank you!

**Comment by gwenchee** [comment]
I am going to merge https://github.com/arfc/2019-chee-wm-poster/pull/4 and make a new PR with your comments

**Comment by katyhuff** [comment]
Excellent. For the poster printing, use the CFOP associated with the DDCA project. The only CFOP I've probably given you.

**Comment by gwenchee** [comment]
Yup!

**Comment by juliaroessler** [comment]
@gwenchee Here are some suggested edits for your poster!

Objectives:
- Both objectives start with “create” – maybe use a synonym to avoid repetition here?

Motivation:
- Try to clean up acronyms if possible so that the reader understands later on when they are referenced
- “Previous work in studying repository loading _**has**_…”
- S1 & S3 “burnup” vs. “burn up” – these should agree!
- “Irradiation and decay calculations…” – try to eliminate passive voice by including a subject; who or what made these calculations?
- “**_These_** data **_are_**…” – the word data is plural
- “CYCLUS is capable of…” can be shortened to “CYCLUS can…” for brevity
- The two concluding sentences could be combined with a semicolon to improve flow

Cyclus:
- “In CYCLUS…” – to make the sure the sentence easy to follow, you could change “they” to “the facilities” to clarify
- The final sentence is pretty long and contains a lot of information; I suggest breaking it into two sentences, i.e. “This work aims to develop a…to provide CYCLUS with simulation capabilities. From these simulations, we can study…”

Waste Conditioning Model:
- Close the gap between the paragraph and the list to match other lists on the poster

Waste Repository Model:
- Consider moving the definition of thermal criteria up in the paragraph or offset it with dashes in the first sentence to avoid repetition and clarify for readers
- S2 “If the thermal criteria…” – again to avoid repetition in this paragraph this could be rephrased as “If the waste package fails to meet the criteria, the model places it into a buffer.” This also eliminates a “to be” verb
- S3: add a “the” before “waste package surface”; could the end just be simplified to “and the repository’s host geology” instead of including the phrase after the comma?

Thermal Model:
- S1 is perfect!
- S2 – can be rewritten as “If the addition of this new package causes its temperature to exceed the thermal limit…”
- S3 – can be rewritten as “To accurately determine its temperature, the repository uses a thermal model…” to eliminate a “be” verb and move the verb closer to the subject

Transient Outside Model:
- S3 “Temperature solutions…” – I would rearrange this a little: “To calculate…in the repository, the model superimposes temperature solutions for the central waste package **_and the_** adjacent point and line sources.” This is mainly stylistic so it’s up to you!

Quasi-steady-state ‘inside’ model:
- Capitalize subtitle to match others
- S1 – I would replace “since there is” with “because EBS has a” and delete “of EBS” when it appears later in the sentence for clarity
- This paragraph is where I found that I had to look back to find the acronyms from before
- Instead of “Figure 1 shows an example of” maybe replace it with a fancy verb like “maps” or “illustrates”

**Comment by katyhuff** [comment]
Thanks @juliaroessler !

**Comment by gwenchee** [comment]
Thanks @juliaroessler , your comments are really helpful!
